name: Manual Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name"
        required: true
      release_name:
        description: "Tag name"
        required: true
      asset_version:
        default: "0.1"
      asset_name:
        default: "0.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create tag by maven-release plugin
        uses: qcastel/github-actions-maven-release@v1.12.2
        with:
          release-branch-name: "master"
          git-release-bot-name: "auto"
          git-release-bot-email: "auto@orange.com"
          skip-perform: true
          access-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ inputs.tag_name }}
          release_name: Release ${{ inputs.release_name }}

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./target/mqtt2dis-${{ inputs.asset_version }}.zip
          asset_name: mqtt2dis-${{ inputs.asset_name }}.zip
          asset_content_type: application/zip
